import styles from './MyRm.module.css';

export default function MyRm() {

    return (
        <div className={styles.myRm}>
            <table>
                <thead>
                    <tr>
                        <th colSpan={3} className={styles.myRmTitle}>내 RM</th>
                    </tr>
                    <tr className={styles.head}>
                        <th>운동명</th>
                        <th>횟수</th>
                        <th>중량</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>

                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>

                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>

                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>
                    <tr>
                        <td>데드리프트</td>
                        <td>10</td>
                        <td>145lb(65kg)</td>
                    </tr>


                </tbody>
            </table>
        </div>
    );
}