spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaehongbyeon98@gmail.com
    password: ygdrokobkukdqfla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true
  
  mvc:
    static-path-pattern: /static/** # 2. 이렇게 접근할 수 있게 하겠다.
  resoruces:
    static-locations: classpath:/static/ # 1. 여기에 경로를
    add-mapping: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 835331576069-q7uk5f4e605binn5pfab82r4h30bkkig.apps.googleusercontent.com
            clientSecret: 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
            

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/with_crossfit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root : info
  file :
    name: C:/Users/user/Desktop/logs/product.log
    max-history: 9999999
    max-size : 100MB
    
    
    

######## env #######

front-end:
  base-url: http://localhost:3000 
  
jwt:
  name: jwt
  refresh-name: refresh
  secret-key: honghong1234